const jsondata = [
  {
    course_type: 'Certification',
    course_id: '24765',
    course_name: 'Aircraft Maintenance Engineering (AME)',
    courses_could_be: 'Full Time',
    stream_name: 'Engineering',
    duration_year: '4',
    duration_month: '0',
    college_count: 1,
    college_url: '',
    url: 'courses/aircraft-maintenance-engineering-ame',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '27',
    course_tag: 'Certificate',
    stream_id: '10',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3622',
    course_name: 'Certificate Course in Medical Laboratory Technology',
    courses_could_be: 'Full Time',
    stream_name: 'Medical',
    duration_year: '0',
    duration_month: '6',
    college_count: 51,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-medical-laboratory-technology-colleges-in-india',
    url: 'courses/certificate-course-in-medical-laboratory-technology',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '167',
    course_tag: 'UG Certificate',
    stream_id: '15',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '12168',
    course_name: 'Certificate Course in Physiotherapy',
    courses_could_be: 'Full Time',
    stream_name: 'Medical',
    duration_year: '2',
    duration_month: '0',
    college_count: 14,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-physiotherapy-colleges-in-india',
    url: 'courses/certificate-course-in-physiotherapy',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '30',
    course_tag: 'Certificate',
    stream_id: '15',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3661',
    course_name: 'Certificate in Laboratory Techniques [CPLT]',
    courses_could_be: 'Full Time',
    stream_name: 'Medical',
    duration_year: '0',
    duration_month: '6',
    college_count: 8,
    college_url:
      'https://collegedunia.com/courses/certificate-in-laboratory-techniques-cplt-colleges-in-india',
    url: 'courses/certificate-in-laboratory-techniques-cplt',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '167',
    course_tag: 'UG Certificate',
    stream_id: '15',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '6213',
    course_name: 'Certificate in Animation',
    courses_could_be: 'Full Time',
    stream_name: 'Animation',
    duration_year: '0',
    duration_month: '6',
    college_count: 21,
    college_url:
      'https://collegedunia.com/courses/certificate-in-animation-colleges-in-india',
    url: 'courses/certificate-in-animation',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10th',
    course_tag_id: '209',
    course_tag: 'Certificate',
    stream_id: '1113',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1081',
    course_name: 'Certificate Course in French',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '1',
    duration_month: '0',
    college_count: 87,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-french-colleges-in-india',
    url: 'courses/certificate-course-in-french',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '158',
    course_tag: 'UG Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1085',
    course_name: 'Certificate Course in German',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '1',
    duration_month: '0',
    college_count: 72,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-german-colleges-in-india',
    url: 'courses/certificate-course-in-german',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '158',
    course_tag: 'UG Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '11465',
    course_name: 'Certificate Course in Spoken English',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '1',
    duration_month: '0',
    college_count: 63,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-spoken-english-colleges-in-india',
    url: 'courses/certificate-course-in-spoken-english',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10th',
    course_tag_id: '23',
    course_tag: 'Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1127',
    course_name: 'Certificate in English',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '1',
    duration_month: '0',
    college_count: 44,
    college_url:
      'https://collegedunia.com/courses/certificate-in-english-colleges-in-india',
    url: 'courses/certificate-in-english',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '158',
    course_tag: 'UG Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1111',
    course_name: 'Certificate course in Spanish',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '1',
    duration_month: '0',
    college_count: 42,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-spanish-colleges-in-india',
    url: 'courses/certificate-course-in-spanish',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '158',
    course_tag: 'UG Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '8893',
    course_name: 'Certificate Course in Communicative English',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '1',
    duration_month: '0',
    college_count: 41,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-communicative-english-colleges-in-india',
    url: 'courses/certificate-course-in-communicative-english',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '23',
    course_tag: 'Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1072',
    course_name: 'Certificate course in Chinese',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '2',
    duration_month: '0',
    college_count: 30,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-chinese-colleges-in-india',
    url: 'courses/certificate-course-in-chinese',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '158',
    course_tag: 'UG Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1082',
    course_name: 'Certificate Course in Functional English',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '0',
    duration_month: '6',
    college_count: 30,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-functional-english-colleges-in-india',
    url: 'courses/certificate-course-in-functional-english',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10th',
    course_tag_id: '23',
    course_tag: 'Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1091',
    course_name: 'Certificate Course in Library and Information Science',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '1',
    duration_month: '0',
    college_count: 29,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-library-and-information-science-colleges-in-india',
    url: 'courses/certificate-course-in-library-and-information-science',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '158',
    course_tag: 'UG Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1107',
    course_name: 'Certificate Course in Russian',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '1',
    duration_month: '0',
    college_count: 27,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-russian-colleges-in-india',
    url: 'courses/certificate-course-in-russian',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '158',
    course_tag: 'UG Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1133',
    course_name: 'Certificate in Hindi',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '1',
    duration_month: '0',
    college_count: 20,
    college_url:
      'https://collegedunia.com/courses/certificate-in-hindi-colleges-in-india',
    url: 'courses/certificate-in-hindi',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10th',
    course_tag_id: '50',
    course_tag: 'Graduate Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1145',
    course_name: 'Certificate in Insurance Services',
    courses_could_be: 'Full Time',
    stream_name: 'Arts',
    duration_year: '0',
    duration_month: '6',
    college_count: 9,
    college_url:
      'https://collegedunia.com/courses/certificate-in-insurance-services-colleges-in-india',
    url: 'courses/certificate-in-insurance-services',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '158',
    course_tag: 'UG Certificate',
    stream_id: '3',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3935',
    course_name: 'Certificate Course in Tally',
    courses_could_be: 'Full Time',
    stream_name: 'Commerce',
    duration_year: '0',
    duration_month: '6',
    college_count: 77,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-tally-colleges-in-india',
    url: 'courses/certificate-course-in-tally',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '24',
    course_tag: 'Certificate',
    stream_id: '5',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3925',
    course_name: 'Certificate Course in Banking',
    courses_could_be: 'Full Time',
    stream_name: 'Commerce',
    duration_year: '1',
    duration_month: '0',
    college_count: 15,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-banking-colleges-in-india',
    url: 'courses/certificate-course-in-banking',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '159',
    course_tag: 'UG Certificate',
    stream_id: '5',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3938',
    course_name: 'Certificate in Accounting',
    courses_could_be: 'Full Time',
    stream_name: 'Commerce',
    duration_year: '0',
    duration_month: '1',
    college_count: 12,
    college_url:
      'https://collegedunia.com/courses/certificate-in-accounting-colleges-in-india',
    url: 'courses/certificate-in-accounting',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '159',
    course_tag: 'UG Certificate',
    stream_id: '5',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3934',
    course_name: 'Certificate Course in Stock Market',
    courses_could_be: 'Full Time',
    stream_name: 'Commerce',
    duration_year: '1',
    duration_month: '0',
    college_count: 10,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-stock-market-colleges-in-india',
    url: 'courses/certificate-course-in-stock-market',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '159',
    course_tag: 'UG Certificate',
    stream_id: '5',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3920',
    course_name: 'Association of Chartered Certified Accountants [ACCA]',
    courses_could_be: 'Full Time',
    stream_name: 'Commerce',
    duration_year: '2',
    duration_month: '0',
    college_count: 9,
    college_url:
      'https://collegedunia.com/courses/association-of-chartered-certified-accountants-acca-colleges-in-india',
    url: 'courses/association-of-chartered-certified-accountants-acca',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: 'Graduation',
    course_tag_id: '52',
    course_tag: 'Graduate Certificate',
    stream_id: '5',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3928',
    course_name:
      'Certificate Course in Financial Accounting & Taxation [CCFAT]',
    courses_could_be: 'Full Time',
    stream_name: 'Commerce',
    duration_year: '0',
    duration_month: '1',
    college_count: 9,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-financial-accounting-and-taxation-ccfat-colleges-in-india',
    url: 'courses/certificate-course-in-financial-accounting-and-taxation-ccfat',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '159',
    course_tag: 'UG Certificate',
    stream_id: '5',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '18944',
    course_name: 'Chartered Accountant',
    courses_could_be: 'Full Time',
    stream_name: 'Commerce',
    duration_year: '4',
    duration_month: '5',
    college_count: 1,
    college_url: '',
    url: 'courses/chartered-accountant',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: 'Graduation',
    course_tag_id: '24',
    course_tag: 'Certificate',
    stream_id: '5',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '5284',
    course_name: 'Certificate in Web Designing',
    courses_could_be: 'Full Time',
    stream_name: 'Computer Applications',
    duration_year: '1',
    duration_month: '6',
    college_count: 61,
    college_url:
      'https://collegedunia.com/courses/certificate-in-web-designing-colleges-in-india',
    url: 'courses/certificate-in-web-designing',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '160',
    course_tag: 'UG Certificate',
    stream_id: '6',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '5261',
    course_name: 'Certificate Course in Computer Application [CCA]',
    courses_could_be: 'Full Time',
    stream_name: 'Computer Applications',
    duration_year: '0',
    duration_month: '6',
    college_count: 30,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-computer-application-cca-colleges-in-india',
    url: 'courses/certificate-course-in-computer-application-cca',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '160',
    course_tag: 'UG Certificate',
    stream_id: '6',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '11833',
    course_name: 'Certificate Course in JAVA',
    courses_could_be: 'Full Time',
    stream_name: 'Computer Applications',
    duration_year: '0',
    duration_month: '6',
    college_count: 24,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-java-colleges-in-india',
    url: 'courses/certificate-course-in-java',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '25',
    course_tag: 'Certificate',
    stream_id: '6',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '11831',
    course_name: 'Certificate Course in C++',
    courses_could_be: 'Full Time',
    stream_name: 'Computer Applications',
    duration_year: '0',
    duration_month: '3',
    college_count: 15,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-c-colleges-in-india',
    url: 'courses/certificate-course-in-c',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '25',
    course_tag: 'Certificate',
    stream_id: '6',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '5943',
    course_name: 'Certificate Course in Interior Design',
    courses_could_be: 'Full Time',
    stream_name: 'Design',
    duration_year: '0',
    duration_month: '6',
    college_count: 69,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-interior-design-colleges-in-india',
    url: 'courses/certificate-course-in-interior-design',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '162',
    course_tag: 'UG Certificate',
    stream_id: '8',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '5935',
    course_name: 'Certificate Course in Fashion Design',
    courses_could_be: 'Full Time',
    stream_name: 'Design',
    duration_year: '1',
    duration_month: '0',
    college_count: 63,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-fashion-design-colleges-in-india',
    url: 'courses/certificate-course-in-fashion-design',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '162',
    course_tag: 'UG Certificate',
    stream_id: '8',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '11363',
    course_name: 'Certificate in Auto CAD',
    courses_could_be: 'Full Time',
    stream_name: 'Design',
    duration_year: '0',
    duration_month: '6',
    college_count: 15,
    college_url:
      'https://collegedunia.com/courses/certificate-in-auto-cad-colleges-in-india',
    url: 'courses/certificate-in-auto-cad',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '26',
    course_tag: 'Certificate',
    stream_id: '8',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '6475',
    course_name: 'Certificate in CAD',
    courses_could_be: 'Full Time',
    stream_name: 'Design',
    duration_year: '1',
    duration_month: '0',
    college_count: 7,
    college_url:
      'https://collegedunia.com/courses/certificate-in-cad-colleges-in-india',
    url: 'courses/certificate-in-cad',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '162',
    course_tag: 'UG Certificate',
    stream_id: '8',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '4859',
    course_name: 'Certificate Course in Maritime Catering',
    courses_could_be: 'Full Time',
    stream_name: 'Hotel Management',
    duration_year: '0',
    duration_month: '6',
    college_count: 6,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-maritime-catering-colleges-in-india',
    url: 'courses/certificate-course-in-maritime-catering',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '164',
    course_tag: 'UG Certificate',
    stream_id: '11',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '11996',
    course_name:
      'Certificate Course in Hotel and Hospitality Management [CHHM]',
    courses_could_be: 'Full Time',
    stream_name: 'Hotel Management',
    duration_year: '1',
    duration_month: '0',
    college_count: 4,
    college_url: '',
    url: 'courses/certificate-course-in-hotel-and-hospitality-management-chhm',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '28',
    course_tag: 'Certificate',
    stream_id: '11',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '9017',
    course_name: 'Certificate Course in Human Rights',
    courses_could_be: 'Full Time',
    stream_name: 'Law',
    duration_year: '0',
    duration_month: '6',
    college_count: 31,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-human-rights-colleges-in-india',
    url: 'courses/certificate-course-in-human-rights',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '57',
    course_tag: 'Graduate Certificate',
    stream_id: '12',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '6312',
    course_name: 'Certificate Course in Intellectual Property [CCIP]',
    courses_could_be: 'Full Time',
    stream_name: 'Law',
    duration_year: '0',
    duration_month: '4',
    college_count: 13,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-intellectual-property-ccip-colleges-in-india',
    url: 'courses/certificate-course-in-intellectual-property-ccip',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: 'Graduation',
    course_tag_id: '57',
    course_tag: 'Graduate Certificate',
    stream_id: '12',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '6328',
    course_name: 'Certificate in Tourism and Travel Management',
    courses_could_be: 'Full Time',
    stream_name: 'Management',
    duration_year: '3',
    duration_month: '0',
    college_count: 57,
    college_url:
      'https://collegedunia.com/courses/certificate-in-tourism-and-travel-management-colleges-in-india',
    url: 'courses/certificate-in-tourism-and-travel-management',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: 'Graduation',
    course_tag_id: '58',
    course_tag: 'Graduate Certificate',
    stream_id: '13',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '9823',
    course_name: 'Certificate Course in Business Analytics',
    courses_could_be: 'Full Time',
    stream_name: 'Management',
    duration_year: '0',
    duration_month: '6',
    college_count: 22,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-business-analytics-colleges-in-india',
    url: 'courses/certificate-course-in-business-analytics',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: 'Graduation',
    course_tag_id: '165',
    course_tag: 'UG Certificate',
    stream_id: '13',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '11163',
    course_name: 'Certificate in Project Management',
    courses_could_be: 'Full Time',
    stream_name: 'Management',
    duration_year: '1',
    duration_month: '6',
    college_count: 11,
    college_url:
      'https://collegedunia.com/courses/certificate-in-project-management-colleges-in-india',
    url: 'courses/certificate-in-project-management',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
      {
        name: 'Career Options & Jobs',
        url: '/career-options-and-jobs',
      },
      {
        name: 'Syllabus',
        url: '/syllabus',
      },
    ],
    level: 'Graduation',
    course_tag_id: '58',
    course_tag: 'Graduate Certificate',
    stream_id: '13',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '11165',
    course_name: 'Certificate in Human Resources',
    courses_could_be: 'Full Time',
    stream_name: 'Management',
    duration_year: '0',
    duration_month: '3',
    college_count: 10,
    college_url:
      'https://collegedunia.com/courses/certificate-in-human-resources-colleges-in-india',
    url: 'courses/certificate-in-human-resources',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: 'Graduation',
    course_tag_id: '165',
    course_tag: 'UG Certificate',
    stream_id: '13',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '6565',
    course_name: 'Certified Financial Planner [CFP]',
    courses_could_be: 'Full Time',
    stream_name: 'Management',
    duration_year: '0',
    duration_month: '5',
    college_count: 8,
    college_url:
      'https://collegedunia.com/courses/certified-financial-planner-cfp-colleges-in-india',
    url: 'courses/certified-financial-planner-cfp',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
      {
        name: 'Career Options & Jobs',
        url: '/career-options-and-jobs',
      },
      {
        name: 'Syllabus',
        url: '/syllabus',
      },
    ],
    level: 'Graduation',
    course_tag_id: '58',
    course_tag: 'Graduate Certificate',
    stream_id: '13',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1902',
    course_name: 'Certificate in Disaster Management [CDM]',
    courses_could_be: 'Full Time',
    stream_name: 'Management',
    duration_year: '0',
    duration_month: '6',
    college_count: 7,
    college_url:
      'https://collegedunia.com/courses/certificate-in-disaster-management-cdm-colleges-in-india',
    url: 'courses/certificate-in-disaster-management-cdm',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '165',
    course_tag: 'UG Certificate',
    stream_id: '13',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '1914',
    course_name: 'Certificate Programme in Sales and Marketing',
    courses_could_be: 'Full Time',
    stream_name: 'Management',
    duration_year: '1',
    duration_month: '0',
    college_count: 6,
    college_url:
      'https://collegedunia.com/courses/certificate-programme-in-sales-and-marketing-colleges-in-india',
    url: 'courses/certificate-programme-in-sales-and-marketing',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '165',
    course_tag: 'UG Certificate',
    stream_id: '13',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '10661',
    course_name: 'Certificate Program in Supply Chain Management',
    courses_could_be: 'Full Time',
    stream_name: 'Management',
    duration_year: '0',
    duration_month: '2',
    college_count: 5,
    college_url: '',
    url: 'courses/certificate-program-in-supply-chain-management',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: 'Graduation',
    course_tag_id: '58',
    course_tag: 'Graduate Certificate',
    stream_id: '13',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '16419',
    course_name: 'Advanced Management Programme (Manufacturing and Operations)',
    courses_could_be: 'Full Time',
    stream_name: 'Management',
    duration_year: '1',
    duration_month: '0',
    college_count: 2,
    college_url: '',
    url: 'courses/advanced-management-programme-manufacturing-and-operations',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: 'Graduation',
    course_tag_id: '58',
    course_tag: 'Graduate Certificate',
    stream_id: '13',
    type_filter: ['certification', 'graduation'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3638',
    course_name: 'Certificate Course in Research Methodology',
    courses_could_be: 'Full Time',
    stream_name: 'Paramedical',
    duration_year: '0',
    duration_month: '6',
    college_count: 13,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-research-methodology-colleges-in-india',
    url: 'courses/certificate-course-in-research-methodology',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '168',
    course_tag: 'UG Certificate',
    stream_id: '16',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '6530',
    course_name: 'Certificate Course in Yoga',
    courses_could_be: 'Full Time',
    stream_name: 'Science',
    duration_year: '1',
    duration_month: '0',
    college_count: 85,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-yoga-colleges-in-india',
    url: 'courses/certificate-course-in-yoga',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '169',
    course_tag: 'UG Certificate',
    stream_id: '18',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '4880',
    course_name: 'Certificate Course in Information Technology',
    courses_could_be: 'Full Time',
    stream_name: 'Science',
    duration_year: '1',
    duration_month: '0',
    college_count: 33,
    college_url:
      'https://collegedunia.com/courses/certificate-course-in-information-technology-colleges-in-india',
    url: 'courses/certificate-course-in-information-technology',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '169',
    course_tag: 'UG Certificate',
    stream_id: '18',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '3681',
    course_name: 'Certified Course in Food and Nutrition',
    courses_could_be: 'Full Time',
    stream_name: 'Science',
    duration_year: '2',
    duration_month: '0',
    college_count: 26,
    college_url:
      'https://collegedunia.com/courses/certified-course-in-food-and-nutrition-colleges-in-india',
    url: 'courses/certified-course-in-food-and-nutrition',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '169',
    course_tag: 'UG Certificate',
    stream_id: '18',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '4891',
    course_name: 'Certificate In Cosmetology',
    courses_could_be: 'Full Time',
    stream_name: 'Science',
    duration_year: '1',
    duration_month: '0',
    college_count: 13,
    college_url:
      'https://collegedunia.com/courses/certificate-in-cosmetology-colleges-in-india',
    url: 'courses/certificate-in-cosmetology',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '169',
    course_tag: 'UG Certificate',
    stream_id: '18',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '6532',
    course_name: 'Certificate in Yoga Education [C.Y.Ed]',
    courses_could_be: 'Full Time',
    stream_name: 'Science',
    duration_year: '0',
    duration_month: '3',
    college_count: 12,
    college_url:
      'https://collegedunia.com/courses/certificate-in-yoga-education-cyed-colleges-in-india',
    url: 'courses/certificate-in-yoga-education-cyed',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '169',
    course_tag: 'UG Certificate',
    stream_id: '18',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
  {
    course_type: 'Certification',
    course_id: '15737',
    course_name: 'Certificate in  Cloud Computing',
    courses_could_be: 'Full Time',
    stream_name: 'Science',
    duration_year: '0',
    duration_month: '6',
    college_count: 6,
    college_url:
      'https://collegedunia.com/courses/certificate-in-cloud-computing-colleges-in-india',
    url: 'courses/certificate-in-cloud-computing',
    tabs: [
      {
        name: 'Course Overview',
        url: '/',
      },
    ],
    level: '10+2',
    course_tag_id: '32',
    course_tag: 'Certificate',
    stream_id: '18',
    type_filter: ['certification'],
    duration_filter: 'full-time',
  },
]
export default jsondata
