const {
  API_URI,
  NODE_ENV,
  PORT,
  URL_CLIENT_DEVELOPMENT,
  URL_SERVER_DEVELOPMENT,
  URL_CLIENT_STAGING,
  URL_SERVER_STAGING,
  URL_CLIENT_PRODUCTION,
  URL_SERVER_PRODUCTION,
  FILE_UPLOAD_DEFAULT_DESTINATION
} = process.env
const FILE_UPLOAD='/uploads/';
const URL_CLIENT = {
  development: URL_CLIENT_DEVELOPMENT,
  staging: URL_CLIENT_STAGING,
  production: URL_CLIENT_PRODUCTION
}

const URL_SERVER = {
  development: URL_SERVER_DEVELOPMENT || `http://localhost:${PORT || 8000}`+API_URI,
  staging: URL_SERVER_STAGING ? URL_SERVER_STAGING + API_URI : 'http://119.18.52.30:8000'+API_URI,
  production: URL_SERVER_PRODUCTION ? URL_SERVER_PRODUCTION + API_URI : 'http://119.18.52.30:8000'+API_URI
}

const UPLOAD_URL_SERVER = {
  development: URL_SERVER_DEVELOPMENT ? URL_SERVER_DEVELOPMENT + FILE_UPLOAD : `http://localhost:${PORT || 8000}`+FILE_UPLOAD,
  staging: URL_SERVER_STAGING ? URL_SERVER_STAGING + FILE_UPLOAD : 'http://119.18.52.30:8000'+FILE_UPLOAD,
  production: URL_SERVER_PRODUCTION ? URL_SERVER_PRODUCTION + FILE_UPLOAD : 'http://119.18.52.30:8000'+FILE_UPLOAD
}
const UPLOAD_DESTINATION_URL_SERVER = {
  development: URL_SERVER_DEVELOPMENT ? URL_SERVER_DEVELOPMENT + FILE_UPLOAD_DEFAULT_DESTINATION : `http://localhost:${PORT || 8000}`+FILE_UPLOAD_DEFAULT_DESTINATION,
  staging: URL_SERVER_STAGING ? URL_SERVER_STAGING + FILE_UPLOAD_DEFAULT_DESTINATION : 'http://119.18.52.30:8000'+FILE_UPLOAD_DEFAULT_DESTINATION,
  production: URL_SERVER_PRODUCTION ? URL_SERVER_PRODUCTION + FILE_UPLOAD_DEFAULT_DESTINATION : 'http://119.18.52.30:8000'+FILE_UPLOAD_DEFAULT_DESTINATION
}


const ENV = NODE_ENV || 'development'

// @ts-ignore
const BASE_URL_CLIENT = URL_CLIENT[ENV]
// @ts-ignore
const BASE_URL_SERVER = URL_SERVER[ENV]
// @ts-ignore
const FILE_UPLOAD_URL_SERVER = UPLOAD_URL_SERVER[ENV] 
// @ts-ignore
const FILE_UPLOAD_DESTINATION_URL_SERVER = UPLOAD_DESTINATION_URL_SERVER[ENV] 

export { BASE_URL_CLIENT, BASE_URL_SERVER, FILE_UPLOAD_URL_SERVER, FILE_UPLOAD_DESTINATION_URL_SERVER }
